Fix issue #5444
reportImplementationExpectedError: The next node in the tree is not
necessarily consecutive. This happens due to syntax errors, e.g.

    class C { foo(), foo(); }