⚗️ Accept baselines for improved test results
Signed-off-by: Babak K. Shandiz <babak.k.shandiz@gmail.com>

diff --git a/tests/baselines/reference/dependentDestructuredVariables.errors.txt b/tests/baselines/reference/dependentDestructuredVariables.errors.txt
index e3704b567a..7de02531e7 100644
--- a/tests/baselines/reference/dependentDestructuredVariables.errors.txt
+++ b/tests/baselines/reference/dependentDestructuredVariables.errors.txt
@@ -1,8 +1,7 @@
-tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts(314,5): error TS7022: 'value1' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
 tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts(314,5): error TS7031: Binding element 'value1' implicitly has an 'any' type.

-==== tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts (2 errors) ====
+==== tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts (1 errors) ====
     type Action =
         | { kind: 'A', payload: number }
         | { kind: 'B', payload: string };
@@ -318,8 +317,6 @@ tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts(314,5): er
     function foo({
         value1,
         ~~~~~~
-!!! error TS7022: 'value1' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
-        ~~~~~~
 !!! error TS7031: Binding element 'value1' implicitly has an 'any' type.
         test1 = value1.test1,
         test2 = value1.test2,
diff --git a/tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types b/tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types
index 5a0e03dda6..a1e95eade9 100644
--- a/tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types
+++ b/tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types
@@ -1,28 +1,28 @@
 === tests/cases/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment3.ts ===
 const [a, b = a] = [1]; // ok
->a : any
->b : any
->a : any
+>a : number
+>b : number
+>a : number
 >[1] : [number]
 >1 : 1

 const [c, d = c, e = e] = [1]; // error for e = e
->c : any
->d : any
->c : any
+>c : number
+>d : number
+>c : number
 >e : any
 >e : any
 >[1] : [number]
 >1 : 1

 const [f, g = f, h = i, i = f] = [1]; // error for h = i
->f : any
->g : any
->f : any
->h : any
->i : any
->i : any
->f : any
+>f : number
+>g : number
+>f : number
+>h : number
+>i : number
+>i : number
+>f : number
 >[1] : [number]
 >1 : 1

diff --git a/tests/baselines/reference/useBeforeDeclaration_destructuring.types b/tests/baselines/reference/useBeforeDeclaration_destructuring.types
index 935d320353..d1ce6d7c4c 100644
--- a/tests/baselines/reference/useBeforeDeclaration_destructuring.types
+++ b/tests/baselines/reference/useBeforeDeclaration_destructuring.types
@@ -1,11 +1,11 @@
 === tests/cases/compiler/useBeforeDeclaration_destructuring.ts ===
 a;
->a : any
+>a : string

 let {a, b = a} = {a: '', b: 1};
->a : any
->b : any
->a : any
+>a : string
+>b : string | number
+>a : string
 >{a: '', b: 1} : { a: string; b?: number; }
 >a : string
 >'' : ""
@@ -13,7 +13,7 @@ let {a, b = a} = {a: '', b: 1};
 >1 : 1

 b;
->b : any
+>b : string | number

 function test({c, d = c}: Record<string, number>) {}
 >test : ({ c, d }: Record<string, number>) => void