Error: Property is overwritten by later spread
Move the checking from JSX to getSpreadType so that normal objects get
the error too.

Also reword the missing semicolon related error to be less silly.